name: Ping Render Service

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping request
        run: |
          curl -X GET https://your-vercel-project.vercel.app/ping